### ISSUE TITLE
Create CivTile and Subclasses - Epic

### ISSUE THREAD

**Issue by IndiePotato** [IndiePotato/PixelCiv#14]
- [ ] Create `CivTile` subclass of `BaseTile` #2 
- [ ] Create `KingdomTile` subclass of `CivTile` #6
- [ ]  Create `VillageTile` subclass of `CivTile` #4
- [ ] Create `PlayerTile` subclass of `CivTile` #5
