### ISSUE TITLE
Create GeoTile and Subclasses - Epic

### ISSUE THREAD

**Issue by IndiePotato** [IndiePotato/PixelCiv#15]
- [ ] Create `GeoTile` subclass of `BaseTile` #2
- [ ] Create `OceanTile` subclass of `GeoTile` #7 
- [ ] Create `CoastalTile` subclass of `GeoTile` #8
- [ ] Create `ForestTile` subclass of `GeoTile` #12 
- [ ] Create `SandTile` subclass of `GeoTile` #11 
- [ ] Create `SnowTile` subclass of `GeoTile` #13 
- [ ] Create `MountainTile` subclass of `GeoTile` #10 
- [ ] Create `PlainsTile` subclass of `GeoTile` #9
