### ISSUE TITLE
Create Unit and Subclasses - Epic

### ISSUE THREAD

**Issue by IndiePotato** [IndiePotato/PixelCiv#23]
- [ ] Create `BaseUnit` Class #19 
- [ ] Create `Serf` Subclass of `BaseUnit` #20 
- [ ] Create `Warrior` Subclass of `BaseUnit` #21 
- [ ] Create `Vehicle` Subclass of `BaseUnit` #22
